#!/bin/bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
	DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
	SOURCE="$(readlink "$SOURCE")"
	[[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done

export DEPLOY_ROOT_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

source "$DEPLOY_ROOT_DIR/src/common.bash"

if [[ -n "$KDH_REGISTRY_USER" ]]; then
	echo "Logging to GitLab Container Registry with CI credentials..."
	docker login -u "$KDH_REGISTRY_USER" -p "$KDH_REGISTRY_PASSWORD" "$KDH_REGISTRY"
	echo ""
fi

echo "Tagging application as latest..."

if [ "x$1" != "x" ]; then
	echo "Tagging $KDH_REGISTRY_IMAGE:$SHORT-$KDH_SHA as $KDH_REGISTRY_IMAGE:$SHORT-latest"
	export SHORT=$(echo "$1" | cut -d'-' -f2-)
	docker pull $KDH_REGISTRY_IMAGE:$SHORT-$KDH_SHA
        docker tag $KDH_REGISTRY_IMAGE:$SHORT-$KDH_SHA $KDH_REGISTRY_IMAGE:$SHORT-latest
	echo "Pushing to GitLab Container Registry..."
        docker push $KDH_REGISTRY_IMAGE:$SHORT-latest
else
	echo "Tagging $KDH_REGISTRY_IMAGE:$KDH_SHA as $KDH_REGISTRY_IMAGE:latest"
	docker pull $KDH_REGISTRY_IMAGE:$KDH_SHA
        docker tag $KDH_REGISTRY_IMAGE:$KDH_SHA $KDH_REGISTRY_IMAGE:latest
	echo "Pushing to GitLab Container Registry..."
	docker push "$KDH_REGISTRY_IMAGE:latest"
fi
